DETAIL = [
    "Explain the difference between both audios in detail.",
    "Explain the difference between the two audios in detail.",
    "Can you describe the differences between the two audios in detail?",
    "Please provide a detailed comparison of both audio files.",
    "Could you elaborate on the distinctions between the two audio tracks?",
    "Explain the variations between the two audio recordings in detail.",
    "Give a thorough explanation of the differences between both audios.",
    "Can you break down the differences between the two audio clips?",
    "Please detail the differences between the two audio samples.",
    "Could you explain in detail how the two audios differ?",
    "Describe in detail the differences between the two audio files.",
    "Provide a detailed analysis of the differences between both audios.",
    "Can you give a detailed account of the differences between the two audios?",
    "Please explain the differences between the two audio tracks in detail.",
    "Could you provide a detailed explanation of the differences between both audios?",
    "Explain in detail how the two audio recordings differ.",
    "Give a detailed description of the differences between the two audios.",
    "Can you elaborate on the differences between the two audio files?",
    "Please provide a thorough explanation of the differences between both audios.",
    "Could you describe in detail the differences between the two audio tracks?",
    "Explain the differences between the two audio samples in detail.",
    "Give a detailed breakdown of the differences between both audios.",
    "Can you explain in detail the differences between the two audio clips?",
    "Please detail the distinctions between the two audio recordings.",
    "Could you provide a detailed comparison of the two audios?",
    "Describe the differences between the two audio files in detail.",
    "Explain in detail the variations between the two audio tracks.",
    "Give a thorough description of the differences between both audios.",
    "Can you provide a detailed analysis of the differences between the two audios?",
    "Please explain the distinctions between the two audio samples in detail.",
    "Could you elaborate on the differences between the two audio clips?",
    "Describe in detail how the two audio recordings differ.",
    "Explain the differences between the two audio files in detail.",
    "Give a detailed account of the differences between both audios.",
    "Can you provide a thorough comparison of the two audio tracks?",
    "Please describe the differences between the two audio samples in detail.",
    "Could you explain in detail the distinctions between the two audios?",
    "Describe the variations between the two audio clips in detail.",
    "Explain in detail how the two audio files differ.",
    "Give a detailed explanation of the differences between both audios.",
    "Can you elaborate on the distinctions between the two audio recordings?",
    "Please provide a detailed breakdown of the differences between the two audios.",
    "Could you describe in detail the variations between the two audio tracks?",
    "Explain the differences between the two audio samples in detail.",
    "Give a thorough explanation of the differences between both audios.",
    "Can you provide a detailed description of the differences between the two audios?",
    "Please explain the differences between the two audio clips in detail.",
    "Could you elaborate on the differences between the two audio files?",
    "Describe in detail the distinctions between the two audio recordings.",
    "Explain in detail the differences between the two audio tracks.",
    "Give a detailed comparison of the differences between both audios.",
    "Can you provide a thorough explanation of the differences between the two audio samples?",
    "Please describe the variations between the two audio clips in detail.",
    "Could you explain in detail how the two audio files differ?",
    "Describe the differences between the two audio recordings in detail.",
    "Explain the distinctions between the two audio tracks in detail.",
    "Give a detailed analysis of the differences between both audios.",
    "Can you provide a detailed account of the differences between the two audios?",
    "Please elaborate on the differences between the two audio samples in detail.",
    "Could you describe in detail the differences between the two audio clips?",
    "Explain in detail the variations between the two audio files.",
    "Give a thorough description of the differences between both audios.",
    "Can you provide a detailed breakdown of the differences between the two audio recordings?",
    "Please explain the distinctions between the two audio tracks in detail.",
    "Could you elaborate on the differences between the two audio samples?",
    "Describe in detail how the two audio clips differ.",
    "Explain the differences between the two audio files in detail.",
    "Give a detailed explanation of the differences between both audios.",
    "Can you provide a thorough comparison of the two audio recordings?",
    "Please describe the differences between the two audio tracks in detail.",
    "Could you explain in detail the distinctions between the two audios?",
    "Describe the variations between the two audio samples in detail.",
    "Explain in detail how the two audio clips differ.",
    "Give a detailed account of the differences between both audios.",
    "Can you provide a thorough explanation of the differences between the two audio files?",
    "Please elaborate on the distinctions between the two audio recordings in detail.",
    "Could you describe in detail the variations between the two audio tracks?",
    "Explain the differences between the two audio samples in detail.",
    "Give a detailed breakdown of the differences between both audios.",
    "Can you provide a detailed description of the differences between the two audios?",
    "Please explain the differences between the two audio clips in detail.",
    "Could you elaborate on the differences between the two audio files?",
    "Describe in detail the distinctions between the two audio recordings.",
    "Explain in detail the differences between the two audio tracks.",
    "Give a detailed comparison of the differences between both audios.",
    "Can you provide a thorough explanation of the differences between the two audio samples?",
    "Please describe the variations between the two audio clips in detail.",
    "Could you explain in detail how the two audio files differ?",
    "Describe the differences between the two audio recordings in detail.",
    "Explain the distinctions between the two audio tracks in detail.",
    "Give a detailed analysis of the differences between both audios."
  ]

SENTENCE = [
    "Explain the difference between both audios in one extended sentence.",
    "Explain the difference between the two audios in one extended sentence.",
    "Describe the distinction between the two audios in a single, detailed sentence.",
    "Summarize the differences between both audio clips in one comprehensive sentence.",
    "In one extended sentence, explain how the two audio files differ.",
    "Provide a detailed sentence explaining the variation between the two audio recordings.",
    "In a single, elaborate sentence, describe the differences between the two audio tracks.",
    "Explain the contrast between the two audio pieces in one long sentence.",
    "In one detailed sentence, summarize the differences between both audio files.",
    "Describe in one extended sentence how the two audio clips are different.",
    "Provide a comprehensive sentence explaining the differences between the two audio samples.",
    "In one elaborate sentence, explain the distinction between the two audio recordings.",
    "Summarize the differences between the two audio tracks in one detailed sentence.",
    "In a single, extended sentence, describe how the two audio files differ.",
    "Explain the variation between the two audio clips in one comprehensive sentence.",
    "In one detailed sentence, describe the differences between the two audio recordings.",
    "Provide a long sentence explaining the contrast between the two audio tracks.",
    "In one elaborate sentence, summarize the differences between both audio files.",
    "Describe the differences between the two audio samples in one extended sentence.",
    "In a single, detailed sentence, explain how the two audio clips differ.",
    "Summarize the variation between the two audio recordings in one comprehensive sentence.",
    "In one extended sentence, describe the distinction between the two audio tracks.",
    "Explain the differences between the two audio files in one detailed sentence.",
    "In a single, elaborate sentence, summarize how the two audio clips are different.",
    "Provide a comprehensive sentence describing the differences between the two audio recordings.",
    "In one detailed sentence, explain the contrast between the two audio tracks.",
    "Describe the variation between the two audio files in one extended sentence.",
    "In a single, long sentence, explain how the two audio clips differ.",
    "Summarize the differences between the two audio recordings in one detailed sentence.",
    "In one elaborate sentence, describe the distinction between the two audio tracks.",
    "Explain the differences between the two audio samples in one comprehensive sentence.",
    "In a single, extended sentence, summarize how the two audio files are different.",
    "Provide a detailed sentence describing the variation between the two audio clips.",
    "In one long sentence, explain the differences between the two audio recordings.",
    "Describe the contrast between the two audio tracks in one extended sentence.",
    "In a single, detailed sentence, summarize how the two audio files differ.",
    "Explain the distinction between the two audio clips in one comprehensive sentence.",
    "In one elaborate sentence, describe the differences between the two audio recordings.",
    "Summarize the variation between the two audio tracks in one detailed sentence.",
    "In a single, extended sentence, explain how the two audio files are different.",
    "Provide a comprehensive sentence describing the differences between the two audio clips.",
    "In one detailed sentence, explain the contrast between the two audio recordings.",
    "Describe the differences between the two audio tracks in one extended sentence.",
    "In a single, long sentence, summarize how the two audio files differ.",
    "Explain the variation between the two audio clips in one detailed sentence.",
    "In one elaborate sentence, describe the distinction between the two audio recordings.",
    "Summarize the differences between the two audio tracks in one comprehensive sentence.",
    "In a single, extended sentence, explain how the two audio files are different.",
    "Provide a detailed sentence describing the contrast between the two audio clips.",
    "In one long sentence, explain the differences between the two audio recordings.",
    "Describe the variation between the two audio tracks in one extended sentence.",
    "In a single, detailed sentence, summarize how the two audio files differ.",
    "Explain the distinction between the two audio clips in one comprehensive sentence.",
    "In one elaborate sentence, describe the differences between the two audio recordings.",
    "Summarize the variation between the two audio tracks in one detailed sentence.",
    "In a single, extended sentence, explain how the two audio files are different.",
    "Provide a comprehensive sentence describing the differences between the two audio clips.",
    "In one detailed sentence, explain the contrast between the two audio recordings.",
    "Describe the differences between the two audio tracks in one extended sentence.",
    "In a single, long sentence, summarize how the two audio files differ.",
    "Explain the variation between the two audio clips in one detailed sentence.",
    "In one elaborate sentence, describe the distinction between the two audio recordings.",
    "Summarize the differences between the two audio tracks in one comprehensive sentence.",
    "In a single, extended sentence, explain how the two audio files are different.",
    "Provide a detailed sentence describing the contrast between the two audio clips.",
    "In one long sentence, explain the differences between the two audio recordings.",
    "Describe the variation between the two audio tracks in one extended sentence.",
    "In a single, detailed sentence, summarize how the two audio files differ.",
    "Explain the distinction between the two audio clips in one comprehensive sentence.",
    "In one elaborate sentence, describe the differences between the two audio recordings.",
    "Summarize the variation between the two audio tracks in one detailed sentence.",
    "In a single, extended sentence, explain how the two audio files are different.",
    "Provide a comprehensive sentence describing the differences between the two audio clips.",
    "In one detailed sentence, explain the contrast between the two audio recordings.",
    "Describe the differences between the two audio tracks in one extended sentence.",
    "In a single, long sentence, summarize how the two audio files differ.",
    "Explain the variation between the two audio clips in one detailed sentence.",
    "In one elaborate sentence, describe the distinction between the two audio recordings.",
    "Summarize the differences between the two audio tracks in one comprehensive sentence.",
    "In a single, extended sentence, explain how the two audio files are different.",
    "Provide a detailed sentence describing the contrast between the two audio clips.",
    "In one long sentence, explain the differences between the two audio recordings.",
    "Describe the variation between the two audio tracks in one extended sentence.",
    "In a single, detailed sentence, summarize how the two audio files differ.",
    "Explain the distinction between the two audio clips in one comprehensive sentence.",
    "In one elaborate sentence, describe the differences between the two audio recordings.",
    "Summarize the variation between the two audio tracks in one detailed sentence.",
    "In a single, extended sentence, explain how the two audio files are different.",
    "Provide a comprehensive sentence describing the differences between the two audio clips.",
    "In one detailed sentence, explain the contrast between the two audio recordings."
  ]

WORD = [
    "Explain the difference between both audios in few words.",
    "Explain the difference between the two audios in few words.",
    "Summarize the differences between the two audios briefly.",
    "Give a short explanation of how the audios differ.",
    "Describe the key differences between both audios in a few words.",
    "Briefly outline the distinctions between the two audio files.",
    "Provide a concise comparison of the two audios.",
    "Highlight the main differences between the two audio tracks.",
    "In a few words, explain how the audios are different.",
    "Summarize the key points of difference between the audios.",
    "Give a brief overview of the differences between the two audios.",
    "Describe the primary differences between both audio files succinctly.",
    "Provide a short summary of how the audios differ.",
    "Explain the differences between the two audios in a nutshell.",
    "Briefly describe the distinctions between the two audio tracks.",
    "Give a concise explanation of the differences between the audios.",
    "Highlight the key differences between the two audio files.",
    "In a few words, summarize how the audios are different.",
    "Provide a brief comparison of the two audios.",
    "Describe the main points of difference between the audios succinctly.",
    "Give a short overview of the differences between the two audios.",
    "Summarize the primary differences between both audio files briefly.",
    "Explain the distinctions between the two audios in a few words.",
    "Provide a concise summary of how the audios differ.",
    "Highlight the main points of difference between the two audio tracks.",
    "In a nutshell, describe the differences between the audios.",
    "Give a brief explanation of the differences between the two audios.",
    "Summarize the key distinctions between the two audio files.",
    "Provide a short description of how the audios are different.",
    "Describe the primary points of difference between the audios briefly.",
    "Give a concise overview of the differences between the two audios.",
    "Highlight the key distinctions between the two audio tracks.",
    "In a few words, explain the differences between the audios.",
    "Provide a brief summary of how the audios differ.",
    "Describe the main differences between the two audio files succinctly.",
    "Give a short comparison of the differences between the audios.",
    "Summarize the primary distinctions between the two audios briefly.",
    "Explain the key points of difference between the audios in a few words.",
    "Provide a concise description of how the audios are different.",
    "Highlight the main distinctions between the two audio tracks.",
    "In a nutshell, summarize the differences between the audios.",
    "Give a brief overview of the differences between the two audios.",
    "Describe the key points of difference between the audios succinctly.",
    "Provide a short explanation of how the audios differ.",
    "Summarize the main distinctions between the two audio files briefly.",
    "Explain the primary differences between the audios in a few words.",
    "Provide a concise summary of the differences between the two audios.",
    "Highlight the key points of difference between the two audio tracks.",
    "In a few words, describe how the audios are different.",
    "Give a brief comparison of the differences between the two audios.",
    "Summarize the primary points of difference between the audios briefly.",
    "Explain the key distinctions between the two audios in a few words.",
    "Provide a concise overview of how the audios differ.",
    "Highlight the main points of difference between the two audio files.",
    "In a nutshell, describe the distinctions between the audios.",
    "Give a brief explanation of how the audios are different.",
    "Summarize the key points of difference between the two audios.",
    "Provide a short description of the differences between the audios.",
    "Describe the primary distinctions between the two audio tracks briefly.",
    "Give a concise summary of the differences between the two audios.",
    "Highlight the main distinctions between the two audio files.",
    "In a few words, explain how the audios differ.",
    "Provide a brief overview of the differences between the audios.",
    "Describe the key distinctions between the two audio tracks succinctly.",
    "Give a short explanation of the differences between the audios.",
    "Summarize the primary points of difference between the two audios briefly.",
    "Explain the main differences between the audios in a few words.",
    "Provide a concise description of the differences between the two audios.",
    "Highlight the key points of difference between the two audio files.",
    "In a nutshell, summarize how the audios are different.",
    "Give a brief comparison of the differences between the audios.",
    "Summarize the key distinctions between the two audios briefly.",
    "Explain the primary points of difference between the audios in a few words.",
    "Provide a concise overview of the differences between the two audios.",
    "Highlight the main distinctions between the two audio tracks.",
    "In a few words, describe the differences between the audios.",
    "Give a brief summary of how the audios differ.",
    "Summarize the primary distinctions between the two audio files briefly.",
    "Explain the key points of difference between the audios in a few words.",
    "Provide a concise description of how the audios differ.",
    "Highlight the main points of difference between the two audios.",
    "In a nutshell, describe the differences between the two audio tracks.",
    "Give a brief explanation of the differences between the audios.",
    "Summarize the key points of difference between the two audio files.",
    "Provide a short description of how the audios are different.",
    "Describe the primary distinctions between the two audios briefly.",
    "Give a concise summary of the differences between the two audio tracks.",
    "Highlight the main distinctions between the two audios.",
    "In a few words, explain the differences between the two audios.",
    "Provide a brief overview of how the audios differ.",
    "Describe the key points of difference between the two audio files succinctly.",
    "Give a short comparison of the differences between the audios.",
    "Summarize the primary distinctions between the two audios briefly."
]


BOTH = [
    "Caption both audios",
    "Add captions to both audio files",
    "Provide subtitles for both audio tracks",
    "Transcribe both audio recordings",
    "Generate captions for both audio clips",
    "Create subtitles for both audio files",
    "Caption both sound recordings",
    "Add subtitles to both audio tracks",
    "Transcribe both sound files",
    "Generate subtitles for both audio recordings",
    "Create captions for both audio tracks",
    "Add text to both audio files",
    "Provide captions for both sound recordings",
    "Transcribe both audio clips",
    "Generate text for both audio files",
    "Create subtitles for both sound files",
    "Caption both audio recordings",
    "Add text to both sound files",
    "Provide subtitles for both audio clips",
    "Transcribe both audio tracks",
    "Generate captions for both sound recordings",
    "Create text for both audio files",
    "Add captions to both sound files",
    "Provide text for both audio recordings",
    "Transcribe both sound recordings",
    "Generate subtitles for both audio tracks",
    "Create captions for both sound files",
    "Add subtitles to both audio recordings",
    "Provide captions for both audio tracks",
    "Transcribe both sound clips",
    "Generate text for both audio recordings",
    "Create subtitles for both audio clips",
    "Caption both sound files",
    "Add text to both audio recordings",
    "Provide subtitles for both sound files",
    "Transcribe both audio files",
    "Generate captions for both audio recordings",
    "Create text for both sound files",
    "Add captions to both audio recordings",
    "Provide text for both sound recordings",
    "Transcribe both audio clips",
    "Generate subtitles for both sound recordings",
    "Create captions for both audio files",
    "Add subtitles to both sound recordings",
    "Provide captions for both audio clips",
    "Transcribe both sound tracks",
    "Generate text for both audio tracks",
    "Create subtitles for both audio recordings",
    "Caption both audio tracks",
    "Add text to both sound recordings",
    "Provide subtitles for both audio files",
    "Transcribe both sound files",
    "Generate captions for both audio tracks",
    "Create text for both audio recordings",
    "Add captions to both audio clips",
    "Provide text for both audio files",
    "Transcribe both sound recordings",
    "Generate subtitles for both audio files",
    "Create captions for both sound recordings",
    "Add subtitles to both audio tracks",
    "Provide captions for both sound files",
    "Transcribe both audio recordings",
    "Generate text for both sound files",
    "Create subtitles for both audio tracks",
    "Caption both sound recordings",
    "Add text to both audio files",
    "Provide subtitles for both sound recordings",
    "Transcribe both audio files",
    "Generate captions for both sound files",
    "Create text for both audio tracks",
    "Add captions to both sound recordings",
    "Provide text for both audio tracks",
    "Transcribe both sound clips",
    "Generate subtitles for both audio clips",
    "Create captions for both audio recordings",
    "Add subtitles to both sound files",
    "Provide captions for both audio recordings",
    "Transcribe both sound tracks",
    "Generate text for both audio clips",
    "Create subtitles for both sound recordings",
    "Caption both audio files",
    "Add text to both audio tracks",
    "Provide subtitles for both sound recordings",
    "Transcribe both audio tracks",
    "Generate captions for both audio clips",
    "Create text for both sound recordings",
    "Add captions to both audio tracks",
    "Provide text for both sound files",
    "Transcribe both audio recordings",
    "Generate subtitles for both sound files",
    "Create captions for both audio tracks",
    "Add subtitles to both audio files",
    "Provide captions for both sound recordings",
    "Transcribe both sound files",
    "Generate text for both audio files",
    "Create subtitles for both audio tracks"
  ]

FIRST = [
    "Caption the first audio",
    "Add subtitles to the first audio",
    "Transcribe the initial audio",
    "Provide captions for the first audio clip",
    "Generate subtitles for the first audio",
    "Caption the primary audio",
    "Create captions for the first audio",
    "Subtitle the first audio",
    "Transcribe the first audio file",
    "Add captions to the initial audio",
    "Generate a transcript for the first audio",
    "Provide subtitles for the first audio",
    "Caption the first audio recording",
    "Create subtitles for the initial audio",
    "Transcribe the first audio clip",
    "Add captions to the first audio file",
    "Generate captions for the initial audio",
    "Subtitle the initial audio",
    "Provide a transcript for the first audio",
    "Caption the first audio file",
    "Create captions for the primary audio",
    "Transcribe the primary audio",
    "Add subtitles to the initial audio",
    "Generate a transcript for the initial audio",
    "Provide captions for the initial audio",
    "Subtitle the first audio clip",
    "Transcribe the first audio recording",
    "Add captions to the primary audio",
    "Generate subtitles for the initial audio",
    "Provide a transcript for the initial audio",
    "Caption the initial audio",
    "Create subtitles for the first audio file",
    "Transcribe the initial audio clip",
    "Add captions to the first audio recording",
    "Generate captions for the primary audio",
    "Subtitle the first audio file",
    "Provide a transcript for the primary audio",
    "Caption the first audio clip",
    "Create captions for the initial audio file",
    "Transcribe the primary audio clip",
    "Add subtitles to the first audio file",
    "Generate a transcript for the primary audio",
    "Provide captions for the primary audio",
    "Subtitle the primary audio",
    "Transcribe the initial audio recording",
    "Add captions to the initial audio file",
    "Generate subtitles for the primary audio",
    "Provide a transcript for the first audio file",
    "Caption the primary audio",
    "Create subtitles for the first audio recording",
    "Transcribe the first audio segment",
    "Add captions to the primary audio file",
    "Generate captions for the first audio recording",
    "Subtitle the initial audio file",
    "Provide a transcript for the first audio recording",
    "Caption the initial audio clip",
    "Create captions for the primary audio file",
    "Transcribe the primary audio recording",
    "Add subtitles to the first audio recording",
    "Generate a transcript for the first audio recording",
    "Provide captions for the first audio segment",
    "Subtitle the first audio segment",
    "Transcribe the initial audio segment",
    "Add captions to the initial audio recording",
    "Generate subtitles for the first audio segment",
    "Provide a transcript for the initial audio file",
    "Caption the primary audio file",
    "Create subtitles for the initial audio recording",
    "Transcribe the primary audio file",
    "Add subtitles to the primary audio recording",
    "Generate captions for the first audio segment",
    "Subtitle the primary audio file",
    "Provide a transcript for the primary audio file",
    "Caption the first audio segment",
    "Create captions for the first audio segment",
    "Transcribe the initial audio file",
    "Add captions to the first audio segment",
    "Generate a transcript for the initial audio recording",
    "Provide captions for the initial audio recording",
    "Subtitle the initial audio recording",
    "Transcribe the primary audio segment",
    "Add subtitles to the initial audio segment",
    "Generate subtitles for the primary audio file",
    "Provide a transcript for the primary audio recording",
    "Caption the initial audio recording",
    "Create subtitles for the primary audio recording",
    "Transcribe the first audio excerpt",
    "Add captions to the primary audio segment",
    "Generate captions for the initial audio segment",
    "Subtitle the first audio excerpt",
    "Provide a transcript for the first audio segment",
    "Caption the primary audio recording",
    "Create captions for the initial audio segment",
    "Transcribe the primary audio excerpt",
    "Add subtitles to the first audio segment",
    "Generate a transcript for the primary audio segment",
    "Provide captions for the primary audio segment",
    "Subtitle the primary audio segment",
    "Transcribe the initial audio excerpt",
    "Add captions to the initial audio segment",
    "Generate subtitles for the primary audio segment",
    "Provide a transcript for the initial audio segment"
  ]

SECOND = [
    "Caption the second audio",
    "Add subtitles to the second audio",
    "Provide captions for the second audio",
    "Transcribe the second audio",
    "Generate captions for the second audio",
    "Create subtitles for the second audio",
    "Caption the second audio file",
    "Add text to the second audio",
    "Subtitle the second audio track",
    "Insert captions into the second audio",
    "Transcribe the second audio track",
    "Add closed captions to the second audio",
    "Provide subtitles for the second audio",
    "Generate text for the second audio",
    "Create captions for the second audio file",
    "Add subtitles to the second audio track",
    "Caption the second audio recording",
    "Provide text for the second audio",
    "Transcribe the second audio file",
    "Generate subtitles for the second audio track",
    "Create text for the second audio",
    "Add captions to the second audio recording",
    "Subtitle the second audio file",
    "Insert text into the second audio",
    "Transcribe the second audio recording",
    "Add closed captions to the second audio track",
    "Provide captions for the second audio file",
    "Generate text for the second audio track",
    "Create subtitles for the second audio recording",
    "Add captions to the second audio file",
    "Subtitle the second audio recording",
    "Insert captions into the second audio file",
    "Transcribe the second audio track",
    "Add closed captions to the second audio recording",
    "Provide subtitles for the second audio file",
    "Generate captions for the second audio track",
    "Create text for the second audio file",
    "Add subtitles to the second audio recording",
    "Caption the second audio track",
    "Provide text for the second audio file",
    "Transcribe the second audio recording",
    "Generate subtitles for the second audio file",
    "Create captions for the second audio recording",
    "Add captions to the second audio track",
    "Subtitle the second audio recording",
    "Insert text into the second audio file",
    "Transcribe the second audio track",
    "Add closed captions to the second audio file",
    "Provide captions for the second audio recording",
    "Generate text for the second audio recording",
    "Create subtitles for the second audio track",
    "Add captions to the second audio recording",
    "Subtitle the second audio track",
    "Insert captions into the second audio recording",
    "Transcribe the second audio file",
    "Add closed captions to the second audio track",
    "Provide subtitles for the second audio recording",
    "Generate captions for the second audio file",
    "Create text for the second audio recording",
    "Add subtitles to the second audio track",
    "Caption the second audio recording",
    "Provide text for the second audio track",
    "Transcribe the second audio file",
    "Generate subtitles for the second audio recording",
    "Create captions for the second audio track",
    "Add captions to the second audio file",
    "Subtitle the second audio track",
    "Insert text into the second audio recording",
    "Transcribe the second audio file",
    "Add closed captions to the second audio recording",
    "Provide captions for the second audio track",
    "Generate text for the second audio file",
    "Create subtitles for the second audio recording",
    "Add captions to the second audio track",
    "Subtitle the second audio file",
    "Insert captions into the second audio recording",
    "Transcribe the second audio track",
    "Add closed captions to the second audio file",
    "Provide subtitles for the second audio track",
    "Generate captions for the second audio recording",
    "Create text for the second audio track",
    "Add subtitles to the second audio file",
    "Caption the second audio recording",
    "Provide text for the second audio recording",
    "Transcribe the second audio track",
    "Generate subtitles for the second audio file",
    "Create captions for the second audio track",
    "Add captions to the second audio recording",
    "Subtitle the second audio file",
    "Insert text into the second audio track",
    "Transcribe the second audio recording",
    "Add closed captions to the second audio file",
    "Provide captions for the second audio track",
    "Generate text for the second audio recording",
    "Create subtitles for the second audio file"
  ]